// lexical grammar

%lex

%%


\s+ /* 省略 whitespaces */

\d+  return "NUMBER"

[+\-] return "ADDITIVE_OPERATOR"

[*\/] return "MULTIPLICATIVE_OPERATOR"



/lex

// Module include

%{

function BinaryExpression(left,op,right){
  return{ type:'BinaryExpression', op , left,right }
}

%}


// syntactic grammar

// 强制 left-associative 写在越后面 优先级越高
// %left '+'
// %left '*'

%%

Exp : AdditiveExp;


AdditiveExp : AdditiveExp ADDITIVE_OPERATOR MultiplicativeExp { $$ = BinaryExpression($1, $2, $3) }
  | MultiplicativeExp
  ;

MultiplicativeExp : MultiplicativeExp MULTIPLICATIVE_OPERATOR PrimaryExp { $$ = BinaryExpression($1, $2, $3) }
  | PrimaryExp
  ;


PrimaryExp : Literal
          | parenthesizedExp
          ;

Literal : NumericLiteral;


// callback
NumericLiteral : NUMBER { $$ = { type : "NumericLiteral", value:Number($1) } };


// $2 -> Exp
parenthesizedExp: '(' Exp ')' { $$ = $2 };
